#!/usr/bin/env python3
"""Extract raw AAC-LC access units from an MP4 into a C header.

The memory probe feeds these frames to sceAudiocodec with its buffers placed
in different memory regions, to see which regions the Media Engine can read.
Usage: gen_aac_fixture.py <input.mp4> <output.h> [frame_count]
"""
import struct
import sys
from pathlib import Path


def boxes(data, start, end):
    while start + 8 <= end:
        size, kind = struct.unpack_from('>I4s', data, start)
        header = 8
        if size == 1:
            size = struct.unpack_from('>Q', data, start + 8)[0]
            header = 16
        elif size == 0:
            size = end - start
        if size < header or start + size > end:
            raise ValueError(f'bad box {kind!r} at {start}')
        yield kind, start + header, start + size
        start += size


def child(data, start, end, kind):
    for k, a, b in boxes(data, start, end):
        if k == kind:
            return a, b
    raise ValueError(f'missing {kind!r}')


def audio_track(data):
    moov = child(data, 0, len(data), b'moov')
    for kind, a, b in boxes(data, *moov):
        if kind != b'trak':
            continue
        mdia = child(data, a, b, b'mdia')
        hdlr = child(data, *mdia, b'hdlr')
        if data[hdlr[0] + 8:hdlr[0] + 12] == b'soun':
            minf = child(data, *mdia, b'minf')
            return child(data, *minf, b'stbl')
    raise ValueError('no audio track')


def full_box_entries(data, box):
    return struct.unpack_from('>I', data, box[0] + 4)[0], box[0] + 8


def main():
    source, output = Path(sys.argv[1]), Path(sys.argv[2])
    wanted = int(sys.argv[3]) if len(sys.argv) > 3 else 24
    data = source.read_bytes()
    stbl = audio_track(data)

    stsd = child(data, *stbl, b'stsd')
    entry = stsd[0] + 8
    if data[entry + 4:entry + 8] != b'mp4a':
        raise ValueError('audio track is not mp4a')
    channels, _, _, _, rate = struct.unpack_from('>HHHHI', data, entry + 24)
    rate >>= 16

    stsz = child(data, *stbl, b'stsz')
    fixed, count = struct.unpack_from('>II', data, stsz[0] + 4)
    sizes = ([fixed] * count if fixed else
             list(struct.unpack_from(f'>{count}I', data, stsz[0] + 12)))

    n, pos = full_box_entries(data, child(data, *stbl, b'stsc'))
    stsc = [struct.unpack_from('>III', data, pos + 12 * i) for i in range(n)]
    n, pos = full_box_entries(data, child(data, *stbl, b'stco'))
    offsets = list(struct.unpack_from(f'>{n}I', data, pos))

    frames = []
    sample = 0
    for chunk_index, chunk_offset in enumerate(offsets, start=1):
        per_chunk = [e[1] for e in stsc if e[0] <= chunk_index][-1]
        at = chunk_offset
        for _ in range(per_chunk):
            if sample >= count:
                break
            frames.append(data[at:at + sizes[sample]])
            at += sizes[sample]
            sample += 1
    # Skip the encoder-priming frames at the start; they decode to silence
    # and would make an ME that wrote nothing look like one that worked.
    frames = frames[4:4 + wanted]
    if len(frames) < wanted:
        raise ValueError(f'only {len(frames)} audio frames available')

    lines = [
        '/* Generated by native/memprobe/gen_aac_fixture.py from',
        f'   {source.name}. Do not edit. */',
        '#pragma once',
        f'#define MEMPROBE_AAC_RATE {rate}u',
        f'#define MEMPROBE_AAC_CHANNELS {channels}u',
        f'#define MEMPROBE_AAC_FRAMES {len(frames)}u',
        'static const unsigned short memprobe_aac_size[] = {',
        '    ' + ', '.join(str(len(f)) for f in frames) + ',',
        '};',
        'static const unsigned char memprobe_aac_data[] = {',
    ]
    blob = b''.join(frames)
    for i in range(0, len(blob), 16):
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in blob[i:i + 16]) + ',')
    lines.append('};')
    output.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
